### ISSUE TITLE
database error when create agent.

### ISSUE THREAD

**Issue by hrqiang** [paschmann/rasa-ui#136]
relation "agents" does not exist at character 13

**Comment by elvay1** [comment]
Hello @hrqiang 

Please can you give me some informations about the method you employed to create the database?
(and the version of RasaUI you're using if you can)

Thank you!

**Comment by hrqiang** [comment]
@elvay1 I use current git HEAD docker-compose, but create agent fail.

**Comment by elvay1** [comment]
@hrqiang Is it still an issue since the last MR?

**Comment by hrqiang** [comment]
Yes. Still failing with this chrome debug console error(different than last time). 
'''
angular.js:13018 POST http://10.205.5.186:5001/api/v2/agents net::ERR_EMPTY_RESPONSE
(anonymous) @ angular.js:13018
t @ angular.js:12744
(anonymous) @ angular.js:12485
(anonymous) @ angular.js:17396
$digest @ angular.js:18557
$apply @ angular.js:18945
(anonymous) @ angular.js:28106
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
angular.js:15018 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"agent_name":"customer_support"},"url":"/api/v2/agents","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTQ3NzcyOTI4fQ.JFgnHeGnbKAcbGF5ZNROyR5SZouDVJGgqro9RISJ5I0","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"error","resource":{"agent_name":"customer_support"}}
'''

How I reproduce it. 
1. clean up postgrep.
2. build with docker build.
3. comment out nlu-server, core-server and action-server in docker-compose.
3. let docker-compose point to my nlu server, core server. 
4. run 
$ docker-compose up -d.

**Comment by hrqiang** [comment]
@elvay1 Tried using everything from docker-compose and it still failed with same angularjs error.

**Comment by pradeepmvn** [comment]
@hrqiang Can you please test this with lastest Master and reopen another issue if it still exisits.

**Comment by shakedlokits** [comment]
Getting this as well, and stop closing issues you didn't solve! @pradeepmvn 
`ERROR:  relation "agents" does not exist at character`

On docker-compose 
```yml
version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    networks: ['rasa-network']
    ports:
      - 5005:5005
    volumes:
      - ./models/current:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/

  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    networks: ['rasa-network']
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models

  action_server:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    volumes:
      - ./actions:/app/actions
  
  postgres:
    image: postgres:11
    networks: ['rasa-network']
    ports:
      - "5432:5432"
    volumes:
      - "rasauidata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rasaui"
      POSTGRES_DB: "rasaui"

  rasa_ui:       
    image: paschmann/rasa-ui:latest
    networks: ['rasa-network']
    ports:
      - "5001:5001"
    depends_on:
      - "rasa_nlu"
      - "postgres"
    environment:
      rasanluendpoint: "http://rasa_nlu:5000"
      rasacoreendpoint: "http://rasa_core:5005"
      postgresserver: "postgres://postgres:rasaui@postgres:5432/rasaui"

networks: {rasa-network: {}}
volumes: {rasauidata:{}}
```
