### ISSUE TITLE
Provide preconfigure pipeline / config

### ISSUE THREAD

**Issue by beevelop** [paschmann/rasa-ui#217]
In the current (and great) v3 version of Rasa-UI the `config` field is empty by default when creating a new agent. For novice users of Rasa this might be quite confusing. Therefore it would be awesome to provide a sane default value. Something like e.g.:

```yaml
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
  - BILOU_flag: true
    name: CRFEntityExtractor
    features:
      - [low, title, upper]
      - [low, bias, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern]
      - [low, title, upper]
  - name: EntitySynonymMapper
```
